### ISSUE TITLE
Generically handle exception in the fork-worker resulting errors while executing the command_line

### ISSUE THREAD

**Issue by mkiwala** [genome/ptero-shell-command#12]
#11 has the feature that if `subprocess.Popen` fails with errno 2 (the command is not found), it will pass that error along to the error callback endpoint.

The fork-worker should generically handle errors from `subprocess.Popen` by logging the error, and passing a generic error message to the error callback endpoint.  Very specific exceptions (as specific cases are identified) may be handled specially by passing a more specific error message to the error callback endpoint, as in the case of not finding the command.

**Comment by davidlmorton** [comment]
This is implemented already.
